---
- name: Make sure git is installed
  apt:
    name: git
    update_cache: yes
  become: yes

- name: Clone dotfiles repo to {{ user_home_dir }}
  git:
    repo: https://github.com/miciek/dotfiles.git
    dest: "{{ user_home_dir }}/.dotfiles"
    force: yes
  become: yes
  become_user: "{{ machine_user }}"
  register: dotfiles
  until: dotfiles|succeeded
  retries: 10
  delay: 1
  ignore_errors: yes

- name: Link .gitconfig from the dotfiles repo
  file:
    src: "{{ user_home_dir }}/.dotfiles/.gitconfig"
    dest: "{{ user_home_dir }}/.gitconfig"
    state: link
  when: dotfiles|succeeded
  become: yes
  become_user: "{{ machine_user }}"

- name: Link Apps dir from the dotfiles repo
  file:
    src: "{{ user_home_dir }}/.dotfiles/Apps"
    dest: "{{ user_home_dir }}/Apps"
    state: link
  when: dotfiles|succeeded
  become: yes
  become_user: "{{ machine_user }}"
