# Original author: JBKahn, see: https://github.com/JBKahn/provisioning-local/blob/master/roles/common/tasks/font.yml
---
- name: Install source-code-pro - make temp dir
  file:
    path: "{{ user_home_dir }}/adobe_font"
    state: directory
  become: yes
  become_user: "{{ machine_user }}"

- name: Install source-code-pro - download font to {{ user_home_dir }}/adobe_font/source_code_pro.zip
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/archive/1.017R.zip
    dest: "{{ user_home_dir }}/adobe_font/source_code_pro.zip"
    mode: 0755
  become: yes
  become_user: "{{ machine_user }}"
  register: font_download

- name: Install source-code-pro - unzip downloaded font to {{ user_home_dir }}/adobe_font/
  unarchive:
    src: "{{ user_home_dir }}/adobe_font/source_code_pro.zip"
    dest: "{{ user_home_dir }}/adobe_font"
    remote_src: yes
  become: yes
  become_user: "{{ machine_user }}"
  when: font_download|succeeded
  register: font_unzip

- name: Install source-code-pro - make fonts directory
  file:
    path: "{{ user_home_dir }}/.fonts"
    state: directory
  become: yes
  become_user: "{{ machine_user }}"
  when: font_unzip|succeeded

- name: Install source-code-pro - copy fonts
  copy:
    src: "{{ user_home_dir }}/adobe_font/source-code-pro-1.017R/OTF/{{ item }}"
    dest: "{{ user_home_dir }}/.fonts"
    remote_src: yes
    mode: 0755
  with_items:
    - "SourceCodePro-Black.otf"
    - "SourceCodePro-Bold.otf"
    - "SourceCodePro-ExtraLight.otf"
    - "SourceCodePro-Light.otf"
    - "SourceCodePro-Medium.otf"
    - "SourceCodePro-Regular.otf"
    - "SourceCodePro-Semibold.otf"
  register: fonts_copying
  become: yes
  become_user: "{{ machine_user }}"

- name: Install source-code-pro - font cache
  command: fc-cache -f -v
  become: yes
  when: fonts_copying|changed

- name: Install source-code-pro - delete temp directory
  file:
    path: "{{ user_home_dir }}/adobe_font"
    state: absent
  become: yes
  become_user: "{{ machine_user }}"
