---
- name: Installing zsh
  apt: pkg=zsh state=latest
  register: installation
  become: yes

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning

- name: Using my .zshrc and .zshenv
  file:
    src: ~/.dotfiles/{{ item.src }}
    dest: ~/{{ item.dest }}
    state: link
  with_items:
    - { src: '.zshrc', dest: '.zshrc' }
    - { src: '.zshenv', dest: '.zshenv' }
  when: cloning|success

- name: Use my custom oh-my-zsh stuff
  copy:
    src: "{{ ansible_env.HOME }}/.dotfiles/.oh-my-zsh"
    dest: "{{ ansible_env.HOME }}/"
    mode: 0755
  when: cloning|success

- name: change default shell to zsh
  user: name={{ machine_user }} shell=/bin/zsh
  when: cloning|success
  become: yes
