---
- name: Make sure that the setup directory exsists
  file:
    path: "{{ ansible_env.HOME }}/setup"
    state: directory
    mode: 0755

- name: Make sure git is installed
  apt:
    name: git
    update_cache: yes
  become: yes

- name: Make {{ machine_user }} a sudoer
  user: name={{ machine_user }} groups=sudo append=yes
  become: yes

- name: Clone dotfiles repo
  git:
    repo: https://github.com/miciek/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
  register: dotfiles
  become: yes
  become_user: "{{ machine_user }}"

- name: Link .gitconfig from the dotfiles repo
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/.gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    state: link
  when: dotfiles|succeeded
  become: yes
  become_user: "{{ machine_user }}"


- name: Link Apps dir from the dotfiles repo
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/Apps"
    dest: "{{ ansible_env.HOME }}/Apps"
    state: link
  when: dotfiles|succeeded
  become: yes
  become_user: "{{ machine_user }}"
