---
- name: Make sure that the setup directory exsists
  file:
    path: "{{ ansible_env.HOME }}/setup"
    state: directory
    mode: 0755

- name: Make sure git is installed
  apt:
    name: git
    update_cache: yes
  become: true

- name: make {{ machine_user }} a sudoer
  user: name={{ machine_user }} groups=sudo append=yes
  become: yes

- name: Clone dotfiles repo
  git:
    repo: https://github.com/miciek/dotfiles.git
    dest: ~/.dotfiles
  register: dotfiles

- name: Link .gitconfig from the dotfiles repo
  file:
    src: ~/.dotfiles/.gitconfig
    dest: ~/.gitconfig
    state: link
  when: dotfiles|success


- name: Link Apps dir from the dotfiles repo
  file:
    src: ~/.dotfiles/Apps
    dest: ~/Apps
    state: link
  when: dotfiles|success
