---
- name: Create group {{ machine_user }}
  group: name={{ machine_user }} state=present
  become: yes

- name: Create user {{ machine_user }}
  user: name={{ machine_user }} groups=sudo,{{ machine_user }} append=yes home={{ user_home_dir }} generate_ssh_key=true
  become: yes

- name: Set user password
  shell: echo {{ machine_user }}:{{ machine_user }} | sudo chpasswd
