---
- name: Install Atom {{ atom_version }}
  apt:
    deb: "https://github.com/atom/atom/releases/download/v{{ atom_version }}/atom-amd64.deb"
  become: yes
  register: atom_install
  until: atom_install|succeeded
  retries: 10
  delay: 1

- name: Make atom backup cron
  cron: name="atom-backup" minute="0" hour="*" job="{{ user_home_dir }}/.dotfiles/atom/atom-backup.sh > {{ user_home_dir }}/.dotfiles/atom/package-list-backup"
  become: yes
  become_user: "{{ machine_user }}"

- name: Install packages from the backup
  shell: apm install --packages-file {{ user_home_dir }}/.dotfiles/atom/package-list-backup
  become: yes
  become_user: "{{ machine_user }}"

- name: Use my custom config.cson file
  file:
    src: "{{ user_home_dir }}/.dotfiles/atom/config.cson"
    dest: "{{ user_home_dir }}/.atom/config.cson"
    state: link
  become: yes
  become_user: "{{ machine_user }}"
