# role developed based on tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04
---
- name: Add Docker repo key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  become: yes
  register: repo_key_added

- name: Add sources to docker.list
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    line: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    create: yes
  become: yes
  register: sources_added
  when: repo_key_added|success and ansible_distribution == 'Ubuntu'

- name: Install docker-engine
  apt:
    name: docker-engine
    update_cache: yes
    force: yes
  become: yes
  when: sources_added|success

- name: Install docker-compose
  apt:
    name: docker-compose
    update_cache: yes
    force: yes
  become: tyes
  when: sources_added|success
