# Original author: jdauphant, see https://github.com/jdauphant/ansible-role-intellij/blob/master/tasks/main.yml
---
- name: Install needed dependancies
  apt: pkg={{ item }} state=installed
  with_items:
    - tar
    - unzip
  become: yes

- name: Download intellij
  get_url:
    url: "https://download.jetbrains.com/idea/ideaIC-{{intellij_version}}.tar.gz"
    dest: "{{ intellij_tmp }}"
  become: yes
  register: intellij_download
  until: intellij_download|succeeded
  retries: 10
  delay: 1

- name: Ensure installation directory
  file:
    state: directory
    mode: 0755
    dest: "{{ intellij_install_dir }}"
  become: yes

- name: Unarchive intellij
  unarchive:
    src: "{{ intellij_tmp }}"
    dest: "{{ intellij_install_dir }}"
    copy: no
    remote_src: yes
  become: yes

- name: Retrieve intellij dir name
  command: ls -t {{ intellij_install_dir }}
  register: intellij_folder_name
  become: yes

- name: Ensure intellij is configured
  template: src=idea.properties.j2 dest={{ intellij_install_dir }}/{{ intellij_folder_name.stdout_lines.0 }}/bin/idea.properties
  become: yes

- name: Ensure intellij bin exist
  template: src=intellij.j2 dest=/usr/bin/intellij mode=755
  become: yes
