---
- name: Dependencies | Ensure packages for installing and using Java installed
  apt: pkg={{ item }} state=installed
  with_items:
    - python-pycurl
    - ant
    - maven
  become: yes

- name: Install Oracle Java Repo Installer Repository
  apt_repository: repo=ppa:webupd8team/java update-cache=yes
  become: yes

- name: Wizardry to bypass the Oracle License File prompt
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  become: yes

- name: Install Oracle Java 8
  apt: pkg=oracle-java8-installer
  become: yes
