---
- name: Make sure git is installed
  apt:
    name: git
    update_cache: yes
  become: yes

- name: Clone dotfiles repo
  git:
    repo: https://github.com/miciek/dotfiles.git
    dest: "{{ user_home_dir }}/.dotfiles"
    force: true
  become: yes
  become_user: "{{ machine_user }}"
  register: dotfiles_clone
  until: dotfiles_clone|succeeded
  retries: 10
  delay: 1
  ignore_errors: yes
