---
- name: Make sure git is installed
  apt:
    name: git
    update_cache: yes
  become: yes

- name: Clone dotfiles repo
  git:
    repo: https://github.com/miciek/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    force: true
  become: yes
  become_user: "{{ machine_user }}"
