---
- name: Download vim
  apt:
    name: vim
    update_cache: yes
  register: installation
  become: yes

- name: Use my .vimrc
  file:
    src: "{{ user_home_dir }}/.dotfiles/{{ item.src }}"
    dest: "{{ user_home_dir }}/{{ item.dest }}"
    state: link
  with_items:
    - { src: '.vimrc', dest: '.vimrc' }
    - { src: '.selected_editor', dest: '.selected_editor' }
  when: installation|succeeded
  become: yes
  become_user: "{{ machine_user }}"

- name: Use my custom .vim stuff
  file:
    src: "{{ user_home_dir }}/.dotfiles/.vim"
    dest: "{{ user_home_dir }}/.vim"
    state: link
  when: installation|succeeded
  become: yes
  become_user: "{{ machine_user }}"
