---
- name: Download vim
  apt:
    name: vim
    update_cache: yes
  register: installation
  become: yes

- name: Use my .vimrc
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}~/{{ item.dest }}"
    state: link
  with_items:
    - { src: '.vimrc', dest: '.vimrc' }
    - { src: '.selected_editor', dest: '.selected_editor' }
  when: installation|succeeded
  become: yes
  become_user: "{{ machine_user }}"

- name: Use my custom .vim stuff
  copy:
    src: "{{ ansible_env.HOME }}/.dotfiles/.vim"
    dest: "{{ ansible_env.HOME }}/"
    remote_src: true
    mode: 0755
  when: installation|succeeded
  become: yes
  become_user: "{{ machine_user }}"
