---
- name: download vim
  apt:
    name: vim
    update_cache: yes
  register: installation
  become: yes

- name: using my .vimrc
  file:
    src: ~/.dotfiles/{{ item.src }}
    dest: ~/{{ item.dest }}
    state: link
  with_items:
    - { src: '.vimrc', dest: '.vimrc' }
    - { src: '.selected_editor', dest: '.selected_editor' }
  when: installation|success

- name: Use my custom .vim stuff
  copy:
    src: "{{ ansible_env.HOME }}/.dotfiles/.vim"
    dest: "{{ ansible_env.HOME }}/"
    mode: 0755
  when: installation|success
